### ISSUE TITLE
How to run the test?

### ISSUE THREAD

**Issue by Taewa** [jimCresswell/wdio-selenium-grid-setup-test#1]
Hi Jim,
I'd like to know how to use Wdio(v4) with Selenium-grid together.

I cloned your repo and ran `npm i ` and `docker build -t grid .`.
Failed.

I changed
`FROM node` to `FROM node:8.16.0` in 'Dockerfile'.

Able to create an docker image.

Ran `docker run grid`.
And got `ERROR: connect ECONNREFUSED 127.0.0.1:4444`.

I guess a browser doesn't exist in the container.

Could you tell me how to run your test please?

Lastly, I was expecting something like `selenium-grid` on the `package.json` but I couldn't find anything.
Am I misunderstanding something?

Thanks.

**Comment by jimCresswell** [comment]
Hi Taewa,

As I recall these tests were created to reproduce an error condition seen in a more complex setup where I was helping some people troubleshoot a selenium grid within a very restricted network. I think the only reason Docker was involved was to reproduce failure conditions involving running apps in containers on Jenkins nodes (not advised). The tests expect a fully configured grid to be running and visible on the network, they don't put their own one there. If you want to use the "app" and tests as examples go ahead but you'll need to set up a grid separately, or use the wdio standalone server to target local browsers. I suggest you ignore the Docker aspect of things. The dependencies will be massively out of date by now.

Sorry I couldn't be more help, I hope you manage to do what you want.

All the best,
Jim
